server:
  port: 8070

spring:
  application:
    name: consumer-fegin

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000ms
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka
ribbon:
  eureka:
    enabled: true
