server:
  port: 8070

spring:
  application:
    name: consumer-fegin
<<<<<<< HEAD
  redis:
    host: 127.0.0.1

    password:

    port: 6379

    timeout: 6000ms # 连接超时时间（毫秒）

    database: 3 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0

    lettuce:

      pool:

        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）默认 8

        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1

        max-idle: 10 # 连接池中的最大空闲连接默认 8

        min-idle: 0 # 连接池中的最小空闲连接默认 0




=======
  profiles:
     active: dev
  main:
     allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000ms
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0
>>>>>>> 2ebe437e55a34722380637b7e605fe041ab0de18

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka
ribbon:
  eureka:
    enabled: true
