server:
  port: 8080

spring:
  application:
    name: provider
  profiles:
     active: dev
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1908?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: root



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka
